// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exhibitions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createExhibition = `-- name: CreateExhibition :exec
INSERT INTO exhibitions (
    id,
    museum_id,
    title,
    description,
    display_order,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE(
        (
            SELECT MAX(display_order) + 1
            FROM exhibitions
            WHERE museum_id = $2
        ),
        0
    ),
    $5
)
`

type CreateExhibitionParams struct {
	ID          string
	MuseumID    string
	Title       string
	Description string
	CreatedAt   time.Time
}

func (q *Queries) CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error {
	_, err := q.db.Exec(ctx, createExhibition,
		arg.ID,
		arg.MuseumID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const getExhibitionByID = `-- name: GetExhibitionByID :one
SELECT
    id,
    museum_id,
    title,
    description,
    display_order,
    created_at
FROM exhibitions
WHERE id = $1
LIMIT 1
`

type GetExhibitionByIDRow struct {
	ID           string
	MuseumID     string
	Title        string
	Description  string
	DisplayOrder int32
	CreatedAt    time.Time
}

func (q *Queries) GetExhibitionByID(ctx context.Context, id string) (GetExhibitionByIDRow, error) {
	row := q.db.QueryRow(ctx, getExhibitionByID, id)
	var i GetExhibitionByIDRow
	err := row.Scan(
		&i.ID,
		&i.MuseumID,
		&i.Title,
		&i.Description,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listExhibitionsByMuseumID = `-- name: ListExhibitionsByMuseumID :many
SELECT
    id,
    museum_id,
    title,
    description,
    display_order,
    created_at
FROM exhibitions
WHERE museum_id = $1
ORDER BY
    display_order ASC,
    id ASC
`

type ListExhibitionsByMuseumIDRow struct {
	ID           string
	MuseumID     string
	Title        string
	Description  string
	DisplayOrder int32
	CreatedAt    time.Time
}

func (q *Queries) ListExhibitionsByMuseumID(ctx context.Context, museumID string) ([]ListExhibitionsByMuseumIDRow, error) {
	rows, err := q.db.Query(ctx, listExhibitionsByMuseumID, museumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExhibitionsByMuseumIDRow
	for rows.Next() {
		var i ListExhibitionsByMuseumIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MuseumID,
			&i.Title,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
