// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exhibits.sql

package sqlcgen

import (
	"context"
	"time"
)

const createExhibit = `-- name: CreateExhibit :one
INSERT INTO exhibits (id, exhibition_id, title, caption, image_url, display_order, created_at)
VALUES ($1, $2, $3, $4, $5,
    COALESCE((SELECT MAX(display_order) + 1 FROM exhibits WHERE exhibition_id = $2), 0),
    $6)
RETURNING id, exhibition_id, title, caption, image_url, display_order, created_at
`

type CreateExhibitParams struct {
	ID           string
	ExhibitionID string
	Title        string
	Caption      string
	ImageUrl     string
	CreatedAt    time.Time
}

func (q *Queries) CreateExhibit(ctx context.Context, arg CreateExhibitParams) (Exhibit, error) {
	row := q.db.QueryRow(ctx, createExhibit,
		arg.ID,
		arg.ExhibitionID,
		arg.Title,
		arg.Caption,
		arg.ImageUrl,
		arg.CreatedAt,
	)
	var i Exhibit
	err := row.Scan(
		&i.ID,
		&i.ExhibitionID,
		&i.Title,
		&i.Caption,
		&i.ImageUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listExhibitsByExhibitionID = `-- name: ListExhibitsByExhibitionID :many
SELECT id, exhibition_id, title, caption, image_url, display_order, created_at FROM exhibits WHERE exhibition_id = $1 ORDER BY display_order ASC, id ASC
`

func (q *Queries) ListExhibitsByExhibitionID(ctx context.Context, exhibitionID string) ([]Exhibit, error) {
	rows, err := q.db.Query(ctx, listExhibitsByExhibitionID, exhibitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exhibit
	for rows.Next() {
		var i Exhibit
		if err := rows.Scan(
			&i.ID,
			&i.ExhibitionID,
			&i.Title,
			&i.Caption,
			&i.ImageUrl,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExhibitionForExhibit = `-- name: LockExhibitionForExhibit :one
SELECT id FROM exhibitions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockExhibitionForExhibit(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockExhibitionForExhibit, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
