// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateExhibit(ctx context.Context, arg CreateExhibitParams) (Exhibit, error)
	CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error
	GetExhibitionByID(ctx context.Context, id string) (GetExhibitionByIDRow, error)
	ListExhibitionsByMuseumID(ctx context.Context, museumID string) ([]ListExhibitionsByMuseumIDRow, error)
	ListExhibitsByExhibitionID(ctx context.Context, exhibitionID string) ([]Exhibit, error)
	LockExhibitionForExhibit(ctx context.Context, id string) (string, error)
}

var _ Querier = (*Queries)(nil)
