// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exhibitions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createExhibition = `-- name: CreateExhibition :exec

INSERT INTO exhibitions (
    id,
    museum_id,
    title,
    description,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateExhibitionParams struct {
	ID          string
	MuseumID    string
	Title       string
	Description string
	CreatedAt   time.Time
}

// Exhibitionを1件保存する。
//
// Go側のQueryコードはsqlcが自動生成するため、
// pgx.Exec()をRepository内で直接書かない。
func (q *Queries) CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error {
	_, err := q.db.Exec(ctx, createExhibition,
		arg.ID,
		arg.MuseumID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}
