// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exhibitions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createExhibition = `-- name: CreateExhibition :exec

INSERT INTO exhibitions (
    id,
    museum_id,
    title,
    description,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateExhibitionParams struct {
	ID          string
	MuseumID    string
	Title       string
	Description string
	CreatedAt   time.Time
}

// Exhibitionを1件保存する。
func (q *Queries) CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error {
	_, err := q.db.Exec(ctx, createExhibition,
		arg.ID,
		arg.MuseumID,
		arg.Title,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const getExhibitionByID = `-- name: GetExhibitionByID :one
SELECT
    id,
    museum_id,
    title,
    description,
    created_at
FROM exhibitions
WHERE id = $1
LIMIT 1
`

// IDを指定してExhibitionを1件取得する。
//
// :one を指定するとsqlcが
// 1件取得用のGoメソッドを自動生成する。
func (q *Queries) GetExhibitionByID(ctx context.Context, id string) (Exhibition, error) {
	row := q.db.QueryRow(ctx, getExhibitionByID, id)
	var i Exhibition
	err := row.Scan(
		&i.ID,
		&i.MuseumID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
