// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Exhibition struct {
	ID          string
	MuseumID    string
	Title       string
	Description string
	CreatedAt   time.Time
}
