// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	//
	// Exhibitionを1件保存する。
	CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error
	//
	// IDを指定してExhibitionを1件取得する。
	//
	// :one を指定するとsqlcが
	// 1件取得用のGoメソッドを自動生成する。
	GetExhibitionByID(ctx context.Context, id string) (Exhibition, error)
}

var _ Querier = (*Queries)(nil)
