// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	//
	// Exhibitionを1件保存する。
	//
	// Go側のQueryコードはsqlcが自動生成するため、
	// pgx.Exec()をRepository内で直接書かない。
	CreateExhibition(ctx context.Context, arg CreateExhibitionParams) error
}

var _ Querier = (*Queries)(nil)
